def get_structure_from_json(json_data):
    if isinstance(json_data, dict):
        return {key: get_structure_from_json(value) for key, value in json_data.items()}
    elif isinstance(json_data, list):
        return [get_structure_from_json(item) for item in json_data]
    else:
        return type(json_data).__name__

if __name__ == "__main__":
    json_data = [8, 'OnJsonApiEvent', {'data': {'presences': [{'activePlatform': 'windows', 'actor': None, 'basic': '', 'details': None, 'game_name': 'Basiloukoum', 'game_tag': '14ans', 'location': None, 'msg': None, 'name': '', 'parties': [], 'patchline': None, 'pid': '757372ab-6d7a-5b8c-932e-b19b8764ecae@eu2.pvp.net', 'platform': 'PC', 'private': 'ew0KCSJpc1ZhbGlkIjogdHJ1ZSwNCgkic2Vzc2lvbkxvb3BTdGF0ZSI6ICJNRU5VUyIsDQoJInBhcnR5T3duZXJTZXNzaW9uTG9vcFN0YXRlIjogIk1FTlVTIiwNCgkiY3VzdG9tR2FtZU5hbWUiOiAiIiwNCgkiY3VzdG9tR2FtZVRlYW0iOiAiIiwNCgkicGFydHlPd25lck1hdGNoTWFwIjogIiIsDQoJInBhcnR5T3duZXJNYXRjaEN1cnJlbnRUZWFtIjogIiIsDQoJInBhcnR5T3duZXJNYXRjaFNjb3JlQWxseVRlYW0iOiAwLA0KCSJwYXJ0eU93bmVyTWF0Y2hTY29yZUVuZW15VGVhbSI6IDAsDQoJInBhcnR5T3duZXJQcm92aXNpb25pbmdGbG93IjogIkludmFsaWQiLA0KCSJwcm92aXNpb25pbmdGbG93IjogIkludmFsaWQiLA0KCSJtYXRjaE1hcCI6ICIiLA0KCSJwYXJ0eUlkIjogIjkwOTQ0NmM4LWFiNTEtNGY5MS05NDg2LTljMWZmYmM0YjcxZSIsDQoJImlzUGFydHlPd25lciI6IHRydWUsDQoJInBhcnR5U3RhdGUiOiAiREVGQVVMVCIsDQoJInBhcnR5QWNjZXNzaWJpbGl0eSI6ICJDTE9TRUQiLA0KCSJtYXhQYXJ0eVNpemUiOiA1LA0KCSJxdWV1ZUlkIjogImRlYXRobWF0Y2giLA0KCSJwYXJ0eUxGTSI6IGZhbHNlLA0KCSJwYXJ0eUNsaWVudFZlcnNpb24iOiAicmVsZWFzZS0xMC4wOS1zaGlwcGluZy0zLTM0NzA4MDIiLA0KCSJwYXJ0eVNpemUiOiAxLA0KCSJ0b3VybmFtZW50SWQiOiAiIiwNCgkicm9zdGVySWQiOiAiIiwNCgkicGFydHlWZXJzaW9uIjogMTc0ODA4NzU4NjcyNCwNCgkicXVldWVFbnRyeVRpbWUiOiAiMDAwMS4wMS4wMS0wMC4wMC4wMCIsDQoJInBsYXllckNhcmRJZCI6ICI0MjAyZDdkNC00YTBkLTNmMzYtNGViNy1jOWI0MGZmZTlhY2YiLA0KCSJwbGF5ZXJUaXRsZUlkIjogIiIsDQoJInByZWZlcnJlZExldmVsQm9yZGVySWQiOiAiIiwNCgkiYWNjb3VudExldmVsIjogMTYsDQoJImNvbXBldGl0aXZlVGllciI6IDAsDQoJImxlYWRlcmJvYXJkUG9zaXRpb24iOiAwLA0KCSJpc0lkbGUiOiBmYWxzZSwNCgkidGVtcFZhbHVlWCI6ICIiLA0KCSJ0ZW1wVmFsdWVZIjogIiIsDQoJInRlbXBWYWx1ZVoiOiBmYWxzZSwNCgkidGVtcFZhbHVlVyI6IGZhbHNlLA0KCSJ0ZW1wVmFsdWVWIjogMSwNCgkicHJlbWllclByZXNlbmNlRGF0YSI6DQoJew0KCQkicm9zdGVySWQiOiAiIiwNCgkJInJvc3Rlck5hbWUiOiAiIiwNCgkJInJvc3RlclRhZyI6ICIiLA0KCQkiZGl2aXNpb24iOiAwLA0KCQkic2NvcmUiOiAwLA0KCQkidGVtcFZhbHVlQSI6IDAsDQoJCSJ0ZW1wVmFsdWVCIjogZmFsc2UsDQoJCSJ0ZW1wVmFsdWVDIjogZmFsc2UsDQoJCSJ0ZW1wVmFsdWVEIjogZmFsc2UNCgl9DQp9', 'privateJwt': None, 'product': 'valorant', 'puuid': '757372ab-6d7a-5b8c-932e-b19b8764ecae', 'region': 'eu2', 'resource': 'RC-1317033593', 'state': 'chat', 'summary': '', 'time': 1748087587273}]}, 'eventType': 'Update', 'uri': '/chat/v4/presences'}]
    structure = get_structure_from_json(json_data)
    import pprint
    pprint.pprint(structure)